/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_glorrian_cmakegradleplugin_testjnilibrary_JNILinker */

#ifndef _Included_dev_glorrian_cmakegradleplugin_testjnilibrary_JNILinker
#define _Included_dev_glorrian_cmakegradleplugin_testjnilibrary_JNILinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_glorrian_cmakegradleplugin_testjnilibrary_JNILinker
 * Method:    doubleInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_glorrian_cmakegradleplugin_testjnilibrary_JNILinker_doubleInt
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
