/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNILibrary */

#ifndef _Included_JNILibrary
#define _Included_JNILibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNILibrary
 * Method:    callLibrary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNILibrary_callLibrary
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
